# frozen_string_literal: true

source "https://rubygems.org"

gem 'gamefic'
gem 'gamefic-standard'

group :development do
  gem 'gamefic-sdk'
  gem 'gamefic-tty'
  gem 'gamefic-opal'
  gem 'rake'
end
