require 'bundler/setup'
require 'gamefic-sdk'

# Add the default Gamefic tasks for building and running games
# Run `rake --tasks` for a list of commands and descriptions
Gamefic::Sdk::Tasks.define_all
